Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/08/2020
Var
// Seção de Declarações das variáveis 
i,m, total :inteiro

Inicio
i<-1
      enquanto total < 1000 faca
i<- i+1
m<-7
total<-m *i
     escreval("7 x ",i," = ",total)
     fimenquanto


Fimalgoritmo