Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
//Faça um algoritmo que:
//a) Leia um número inteiro;
//b) Leia um segundo número inteiro;
//c) Efetue a adição dos dois valores;
//d) Apresente o valor calculado.

Var
a,b, resultado:inteiro

Inicio
      Escreva("Digite o 1° número: ")
      leia(a)
      escreva("Digite o 2° número: ")
      leia(b)
      resultado<-a+b
      escreva("A soma a e b = ",resultado)


Fimalgoritmo