Algoritmo "semnome"
//Faça um algoritmo que calcule a área de um triângulo, considerando a fórmula
//(base*altura)/2. Utilize as variáveis AREA, BASE e ALTURA e os
//operadores aritméticos de multiplicação e divisão.
Var
area, base, altura:real

Inicio
   escreval("Digite o número da base: ")
   leia (base)
   escreval("Digite o número da altura: ")
   leia(altura)
   area<-(base*altura)/2
   escreval("A área deste triangulo é: ",area )


Fimalgoritmo