Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
var
 num:vetor [1..10]de inteiro
 i:inteiro

Inicio

    para i de 1 ate 10 faca
    escreva("Digite um número: ")
    leia(num[i])
    fimpara
    
    escreval("Ordem dos números digitados: ")
    para i de 1 ate 10 faca
    escreva(num[i])
    fimpara
    
fimalgoritmo