Algoritmo  " testebeta"
// Professor   : Silvia
// Descrição   : Crie um algoritmo (Visualg para escrever 1000 x  Proa 4.0
//Voltaremos as 10:20
// Data atual  : 10/08/2020
Var
a, c: inteiro
b:caractere
Inicio
      escreval ("Digite frase a ser repetida: ")
      leia (b)
      escreval("Quantas vezes: ")
      leia (c)
      

         para c<-1 ate c faca
         escreval (b)


      fimpara
Fimalgoritmo